import { NzCronExpressionModule } from 'ng-zorro-antd/cron-expression';
import { Component, OnInit  } from '@angular/core';
import {HttpClient} from '@angular/common/http';
import { CrudHttpService } from '../crud-http-service.service';
import { NzButtonSize } from 'ng-zorro-antd/button';
import { Router } from '@angular/router';
import { NzNotificationService } from 'ng-zorro-antd/notification';
import { DatePipe } from '@angular/common';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Papa } from 'ngx-papaparse';
import { UserServiceService } from '../user-service.service';


@Component({
  selector: 'app-attendance',
  templateUrl: './attendance.component.html',
  styleUrls: ['./attendance.component.css']
})
export class AttendanceComponent implements OnInit {

  size: NzButtonSize = 'large';
  searchValue = '';
  searchDate:any;
  visible = false;
  dateEx:any;
  date = null;
  Date:any ;
  isCollapsed = true;
  editCache: { [key: number]: { edit: boolean; data: AttendanceList } } = {};
  attendance_list: AttendanceList[] = [];
  employee_list: EmployeeList[] = [];
  attendance_list_add: AttendanceList_add[] = [];
  timeEx: any;
  // attendees_list: attendees[] = [];

  // final_list: list[] = [];

  // update_list: updatelist[] =[];

//export table

exportTableToExcel():void {

  console.log('Download');
  const downloadLink = document.createElement('a');
  const dataType = 'application/vnd.ms-excel';
  const table = document.getElementById('attendance_sheet');
  const tableHtml = table?.outerHTML.replace(/ /g, '%20');
  document.body.appendChild(downloadLink);
  downloadLink.href = 'data:'+ dataType + ' ' + tableHtml;
  downloadLink.download = 'attendance_sheet.xls';
  downloadLink.click();
  console.log('Download');

}


generateCSV() {
  // Get the table element
  const table = document.getElementById('attendance_sheet');

  // Get all rows from table
  const rows = table!.querySelectorAll('tr');

  // Set the table headers

  const headers = ['DATE','','FIRST NAME', 'LAST NAME', 'POSITION', 'DEPARTMENT', 'TIME-IN', 'TIME-OUT', 'STATUS'];


  // Create a new array to hold the table data
  const data = [];

  // Loop through each row and extract the cell data
  for (let i = 1; i < rows.length; i++) {
    const row = [];
    const cells = rows[i].querySelectorAll('td');
    for (let j = 0; j < cells.length; j++) {
      row.push(cells[j].textContent);
    }
    data.push(row);
  }


  const sanitizedData = data.map(row => row.map(val => val === null ? '' : val));

  this.dateEx =this.datepipe.transform((new Date), 'MMMM d, y');
  this.timeEx =this.datepipe.transform((new Date), 'hh:mm a');

  var export_date = this.papa.unparse({
    "fields": ["Export Date and Time : ",this.dateEx ,this.timeEx],
    "data": [

    ]
  });

  var title = this.papa.unparse({
    "fields": ["Attendance Record List"],
    "data": [

    ]
  });

  var admin_name = this.papa.unparse({
    "fields": ["Generated by : ", this.user.getUserName()],
    "data": [

    ]
  });

  // Convert the data array to a CSV string using Papa Parse
  const csvString = this.papa.unparse(

    {

    fields: headers,
    data: sanitizedData,

  });

  // Create a new blob with the CSV string and set the content type to CSV
  const blob = new Blob([export_date,'\n',title,'\n',csvString,'\n\n\n',admin_name], {type: 'text/csv'});

  // Create a link element to download the CSV file
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = 'Attendance Record.csv';
  document.body.appendChild(link);

  // Click the link element to download the CSV file
  link.click();

  // Remove the link element from the DOM
  document.body.removeChild(link);
}



generatePDF() {
  const doc = new jsPDF('l', 'mm', [330, 210]);

  doc.text("Attendance List Record",10,10)
  // Get the table element
  const table = document.getElementById('attendance_sheet');


  const table2Data = [
    []

  ];
  this.dateEx =this.datepipe.transform((new Date), 'MMMM d, y');
  this.timeEx =this.datepipe.transform((new Date), 'hh:mm a');

  const headers2 = ['Generated by :', this.user.getUserName()];
  const date = ["Export Date and Time : ",this.dateEx+' '+this.timeEx];


  const tableWidth2 = 100;
  const columnWidths2 = [20, 20, 20];
  const tableHeight2 = table2Data.length * 10;


  (doc as any).autoTable({
    head: '',
    body: [headers2,date],
    startY:20,
    tableWidth: tableWidth2,
    columnWidth: columnWidths2,
    height: tableHeight2
  });



  // Get all rows from table
  const rows = table!.querySelectorAll('tr');

  // Set the table headers
  const headers = ['Date','', 'First Name', 'Last Name', 'Position','Department', 'Time-in','Time-out','Status'];

  // Create a new array to hold the table data
  const data = [];

  // Loop through each row and extract the cell data
  for (let i = 1; i < rows.length; i++) {
    const row = [];
    const cells = rows[i].querySelectorAll('td');

    for (let j = 0; j < cells.length; j++) {
      row.push(cells[j].textContent);
    }

    data.push(row);
  }

  // Set the table width and column widths
  const tableWidth = 300;
  const columnWidths = [10, 30, 30, 30, 25, 25, 40, 25, 25, 30, 20, 25];

  // Calculate the table height based on the number of rows
  const tableHeight = data.length * 10;

  // Add the table to the PDF using the autoTable plugin
  (doc as any).autoTable({
    head: [headers],
    body: data,
    startY: 50,
    tableWidth: tableWidth,
    columnWidth: columnWidths,
    height: tableHeight
  });


  // Save the PDF
  doc.save('Attendance List Record.pdf');
}








  //notification
  deleteNotif(): void {
    this.notification.create(
      'success',
      'Successful',
      'Delete user complete',
      {

        nzStyle: {
          width: '600px',
          marginLeft: '-265px',
          backgroundColor:'rgba(241, 255, 246, 0.900)',
        },
        nzClass: 'notification',

      }

    );
  }
  updateNotif(): void {
    this.notification.create(
      'success',
      'Successful',
      'Update Attendance complete',
      {

        nzStyle: {
          width: '600px',
          marginLeft: '-265px',

           backgroundColor:' rgba(241, 255, 246, 0.900)',
        },
        nzClass: 'notification',

      }

    );
  }


  //update User
 startEdit(id: number): void {
    this.editCache[id].edit = true;
  }

  cancelEdit(id: number): void {
    const index = this.attendance_list.findIndex(item => item.id === id);
    this.editCache[id] = {
      data: { ...this.attendance_list[index] },
      edit: false
    };
  }

  saveUser(id: number): void {
    const index = this.attendance_list.findIndex(item => item.id === id);
    Object.assign(this.attendance_list[index], this.editCache[id].data);




        this.crudHttpService.updateattendance(id,this.editCache[id].data).subscribe((response)=>{
          this.updateNotif();
          this.attendanceList();
              },(error=>{

        }));

    this.editCache[id].edit = false;
  }
  updateEditCache(): void {
    this.attendance_list.forEach(item => {
      this.editCache[item.id] = {
        edit: false,
        data: { ...item }

      };

    });
  }





  ngOnInit(): void {
    this.attendanceList();
    this.employeeList()
    this.search();

  }

  //get all employee attendance
  attendanceList(){
    this.crudHttpService.attendancelist().subscribe((Response)=>{

      console.log('Response');
      console.log(Response);

      this.attendance_list = Object.values(Response);





      this.updateEditCache();
      },(error=>{

      }));

  }
  employeeList(){
    this.crudHttpService.employeelist().subscribe((Response)=>{
      console.log('Response');
      console.log(Response);
      this.employee_list = Object.values(Response);
      this.updateEditCache();
      },(error=>{

      }));

  }






//delete user

  deleteEmployee(attendance: any){
    this.crudHttpService.deleteattendance(attendance).subscribe((response)=>{
      this.deleteNotif();
      this.attendanceList();
    },(error=>{
    }));
  }





//search user
  reset(): void {
    this.searchValue = '';
    this.searchDate='';
    this.attendanceList();
  }

  search(): void {

    this.visible = false;
    this.attendance_list = this.attendance_list.filter((item: AttendanceList) => item.date.indexOf(this.searchValue) !== -1);
    console.log(this.attendance_list);
    this.searchValue = '';

  }



//search date
onChange(result: Date): void {

  if (result == null) {
    this.attendanceList();
    this.onChange(this.Date);
  }


this.searchDate = this.datepipe.transform((result), 'MMMM d, y');


  this.visible = false;
  this.attendance_list = this.attendance_list.filter((item: AttendanceList) => item.date.indexOf(this.searchDate) !== -1);
  console.log(this.attendance_list);
  console.log('onChange: ', result);
}



  constructor(private user:UserServiceService,private papa: Papa,public datepipe: DatePipe,private notification:NzNotificationService,private _http:HttpClient, private crudHttpService: CrudHttpService, private router:Router) {

  let currentDateTime =this.datepipe.transform((new Date), 'MMMM d, y h:mm:ss a');
      this.Date =  currentDateTime;
     console.log(currentDateTime);
      this.onChange(this.Date);


  }



}

interface AttendanceList {
      currentDateTime: any;
      id:number;
      date:string;
      attendance: string;
      attendees:{
        image:string;
        id:number;
        fname: string;
        mname: string;
        lname: string;
        position: string;
        department: string;
        time_in:string;
        time_out:string;
      }

}






interface EmployeeList {
  id:number;
  userName: string;
  password: string;
  accessType: string;
  fname: string;
  mname: string;
  lname: string;
  email: string;
  number: string;
  position: string;
  department: string;
  attendance: string;
  image:string;
  apply:{
    type:string;
    date_to:string;
    date_from:string;
    reason:string;
    approval:string;
  }
}


interface AttendanceList_add {
  currentDateTime: any;
  id:number;
  date:string;
  attendance: string;
  attendees:{
    image:string;
    id:number;
    fname: string;
    mname: string;
    lname: string;
    position: string;
    department: string;
    time_in:string;
    time_out:string;
  }

}


